version: "3.8"

services:

  habits:
    build: .
    ports:
      - 16969:6969

  prometheus:
    image: bitnami/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 19090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 13000:3000
    volumes:
      - grafana-data:/var/lib/grafana
  
  node_exporter:
    image: bitnami/node-exporter
    ports:
      - 19100:9100
  
  blackbox_exporter:
    image: bitnami/blackbox-exporter
    ports:
      - 19115:9115
  

volumes:
  grafana-data: