# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - "alertmanager:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "alert_rules.yml"

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:

  - job_name: "habits"
    static_configs:
      - targets: ["habits:6969"]
    basic_auth: 
      username: "yerkebulan"
      password: "asdasd"
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
    scrape_interval: 30s
    scrape_timeout: 10s
  
  - job_name: "blackbox_exporter"
    static_configs:
      - targets: ["blackbox_exporter:9115"]
    scrape_interval: 30s
    scrape_timeout: 10s